sudo: false
language: c++
compiler:
    - g++

addons:
    apt:
        sources:
          - debian-sid
        packages:
            - gcc-multilib
            - gcc-arm-none-eabi
            - libusb-dev

script:
    - make clean all
